### ISSUE TITLE
'map' object has no attribute 'reshape'

### ISSUE THREAD

**Issue by turovapolina** [drumichiro/nmf-and-ntf#1]
Hello @drumichiro!

I am trying to use NTF with your code and unfortunately an error occured:
![image](https://user-images.githubusercontent.com/61549119/90860802-58ef5900-e393-11ea-9da5-c81685ea5049.png)
I used your file ntf.py with your examples of tensors.
Could you please have a look? Thank you very much in advance!

Best regards,
Polina

**Comment by drumichiro** [comment]
Hi, @turovapolina,

Sorry for the late reply.
Let me know how to reproduce this error. If you encountered the error using your original script, could you share either the original one or a simple code based on it (to reproduce this issue easily)?

**Comment by turovapolina** [comment]
Dear @drumichiro,

Thank you very much for your reply!
I just simply copied your file ntf.py and it has an example of test tensor  in it.
I ran it without any changes and this error occur.
Did I do anything incorrect? 
Error evolved when code try to get attribute 'reshape' (tensor.reshape(self.shape)) from tensor constructed by these lines:
tensor = self.composeTensor(self.factor)
tensor = np.sum(tensor, axis=0)

Best regards,
Polina

**Comment by drumichiro** [comment]
Hi, @turovapolina,

I succeeded in reproducing almost the same error by running a demo script on python 3.5 after replacing print "" with print(""). I guess you used either python~3.5 or later than 3.5 on your environment, is it correct?

As you can see "print" without parentheses"()", these scripts were written assuming that they are working on python~2.7.

Anyway, as I think python\~2.7 is too old to be used, I'll update all scripts to support python\~3.5.

**Comment by drumichiro** [comment]
Hi, @turovapolina,

I've made all scripts support python~3.5 at this commit ([357835e3](https://github.com/drumichiro/nmf-and-ntf/commit/357835e3810eb47c2403af4acc2e499755fd042b)).

After you can confirm the HEAD is working well without what you reported, please close this issue. Thank you for reporting this thing.

**Comment by turovapolina** [comment]
Dear @drumichiro,

Yes, you are right! I am using python 3 and I replaced print"" with print (""), I just forgot that I did it.
Your updated scripts work fine now.
Thank you very much for you help!

Best regards,
Polina
